servers:
  broadcast:
    bind_address: 192.168.2.255
    port: 10000
  public:
    bind_address: 0.0.0.0
    port: 10001
  private:
    port: 10002
  admin:
    bind_address: 0.0.0.0
    port: 10003
sweeping:
  pages:
   base_dir: /home/pgte/dev/sweepytest
   # allowed_paths match is done using File.fnmatch expressions: http://www.ruby-doc.org/core/classes/File.html#M002519
   allowed_paths: [dev, dev/*]
  fragments:
   base_dir: /home/pgte/dev/sweepytest/tmp/cache
  
persistence:
  persist: true
  peers: [192.168.2.100]
  retry_after_secs: 10 
  # the amount of time the retries will try to send this message 
  timeout_secs: 1000